# 创建一个 ndarray 
numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)
- object	数组或嵌套的数列
- dtype	数组元素的数据类型，可选
- copy	对象是否需要复制，可选
- order	创建数组的样式，C为行方向，F为列方向，A为任意方向（默认）
- subok	默认返回一个与基类类型一致的数组
- ndmin	指定生成数组的最小维度

In [ ]:
import numpy as np

In [7]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [8]:
print(a)

[1 2 3 4]


In [10]:
# 多于一个维度
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [11]:
# 最小维度
np.array([1, 2, 3, 4, 5], ndmin=2)

array([[1, 2, 3, 4, 5]])

In [12]:
# dtype 参数
np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

注意，无论多少维度，实际的数据存储都是一维连续的。