# 数组属性
- 维数称为秩（rank）,秩就是轴的数量.
- 轴（axis），也就是维度（dimensions）
- axis=0，表示沿着第 0 轴进行操作，即对每一列进行操作
- axis=1，表示沿着第1轴进行操作，即对每一行进行操作

## 属性
| 属性 | 说明 |
| :--- | :--- |
| 属性 | 说明 |
| ndarray.ndim     | 秩，即轴的数量或维度的数量 |
| ndarray.shape    | 数组的维度，对于矩阵，n 行 m 列 |
| ndarray.size     | 数组元素的总个数，相当于 .shape 中 n*m 的值 |
| ndarray.dtype    | ndarray 对象的元素类型 |
| ndarray.itemsize | ndarray 对象中每个元素的大小，以字节为单位 |
| ndarray.flags    | ndarray 对象的内存信息 |
| ndarray.real     | ndarray元素的实部 |
| ndarray.imag     | ndarray 元素的虚部 |
| ndarray.data     |包含实际数组元素的缓冲区，由于一般通过数组的索引获取元素，所以通常不需要使用这个属性。|

In [1]:
import numpy as np

# ndim

In [3]:
a = np.arange(24)
print(a.ndim)
b = a.reshape(2, 4, 3)
print(b.ndim)

1
3


# shape

In [4]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.shape

(2, 3)

In [5]:
a

array([[1, 2, 3],
       [4, 5, 6]])

# 改变 shape 的两种方式

In [7]:
# 改变 shape, 直接给shape 赋值也可
a.shape = (3, 2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
# 改变 shape，使用 reshape 函数也可
b = a.reshape(6)
# 注意 a 没有变化，所以 reshape 函数不是一个原地操作
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
# b 是 reshape 的返回值，它才体现出来变化
b

array([1, 2, 3, 4, 5, 6])

# itemsize
单个元素所占的字节数

In [14]:
x = np.array([1, 2, 3, 4, 5], dtype=np.int8) 
x.itemsize

1

In [15]:
np.array([1, 2, 3], dtype=np.float64).itemsize

8

# flags
数组对象的内存信息，包括: 

| 属性	| 描述 |
| :--- | :--- |
| C_CONTIGUOUS (C)	| 数据是在一个单一的C风格的连续段中 |
| F_CONTIGUOUS (F)	| 数据是在一个单一的Fortran风格的连续段中 |
| OWNDATA (O)	    | 数组拥有它所使用的内存或从另一个对象中借用它 | 
| WRITEABLE (W)	    | 数据区域可以被写入，将该值设置为 False，则数据为只读 | 
| ALIGNED (A)	    | 数据和所有元素都适当地对齐到硬件上 | 
| UPDATEIFCOPY (U)	| 这个数组是其它数组的一个副本，当这个数组被释放时，原数组的内容将被更新 | 

In [16]:
np.array([1, 2, 3, 4, 5]).flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False