# 创建数组
## numpy.empty
创建未经初始化的数组，所以数组中的值没有规律可言.

numpy.empty(shape, dtype=float, order='C')

In [2]:
import numpy as np

In [4]:
x = np.empty([3, 2], dtype=int)
x

array([[ 1152921504606846976, -3458755719996881581],
       [                   3,                    0],
       [                   0,      844424930131968]])

# numpy.zeros
全 0 填充

numpy.zeros(shape, dtype=float, order='C')

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros((5), dtype=np.int32)

array([0, 0, 0, 0, 0], dtype=int32)

In [8]:
# 这种多一个‘,’的shape有什么不同, 这个例子看不出来差别
np.zeros((5,)) 

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros((2, 2), dtype=[('x', 'i4'), ('y', 'f4')])

array([[(0, 0.), (0, 0.)],
       [(0, 0.), (0, 0.)]], dtype=[('x', '<i4'), ('y', '<f4')])

# numpy.ones
全 1 填充 

numpy.ones(shape, dtype=None, order='C')  # 默认类型还是 float

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.ones([2, 2], dtype=int)

array([[1, 1],
       [1, 1]])

# numpy.eye
单位阵。对角线元素为1，其余元素为0

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])