# numpy 从已有数组创建数组
## numpy.asarray
numpy.asarray(a, dtype=None, order=None)
- a 任意形式的输入参数，可以是，列表, 列表的元组, 元组, 元组的元组, 元组的列表，多维数组

In [3]:
import numpy as np

In [4]:
# 从列表而来
# 此时自动推断了数据类型为 int
np.asarray([1, 2, 3]) 

array([1, 2, 3])

In [5]:
np.asarray((1, 2, 3))

array([1, 2, 3])

In [10]:
x = np.asarray([(1, 2, 3), (4, 5)])
x

/Users/zhangcheng/opt/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return array(a, dtype, copy=False, order=order)


array([(1, 2, 3), (4, 5)], dtype=object)

In [8]:
x.shape

(2,)

In [9]:
x.dtype

dtype('O')

In [11]:
np.asarray([1, 2, 3], dtype=float)

array([1., 2., 3.])

## numpy.frombuffer 
实现动态数组。接受buffer输入参数， 以流的形式读入转化成ndarray 对象

numpy.frombuffer(buffer, dtype=float, count=-1, offset=0)

注意，buffer 是字符串时，python3 默认 str 是unicode 类型，所以要转成 bytestring 在原 str 上加 b 